In [1]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import warnings

warnings.filterwarnings('ignore')

In [2]:
# Load data
data = pd.read_csv('learningSet.csv')

In [3]:
data.shape

(95412, 481)

In [4]:
data.describe()

ODATEDW         TCODE           DOB           AGE       NUMCHLD  \
count  95412.000000  95412.000000  95412.000000  71747.000000  12386.000000   
mean    9141.363256     54.223117   2723.602933     61.611649      1.527773   
std      343.454752    953.844476   2132.241295     16.664199      0.806861   
min     8306.000000      0.000000      0.000000      1.000000      1.000000   
25%     8801.000000      0.000000    201.000000     48.000000      1.000000   
50%     9201.000000      1.000000   2610.000000     62.000000      1.000000   
75%     9501.000000      2.000000   4601.000000     75.000000      2.000000   
max     9701.000000  72002.000000   9710.000000     98.000000      7.000000   

             INCOME       WEALTH1           HIT       MBCRAFT      MBGARDEN  \
count  74126.000000  50680.000000  95412.000000  42558.000000  42558.000000   
mean       3.886248      5.345699      3.321438      0.152075      0.059166   
std        1.854960      2.742490      9.306899      0.470023      0.262078   
min        1.000000      0.000000      0.000000      0.000000      0.000000   
25%        2.000000      3.000000      0.000000      0.000000      0.000000   
50%        4.000000      6.000000      0.000000      0.000000      0.000000   
75%        5.000000      8.000000      3.000000      0.000000      0.000000   
max        7.000000      9.000000    241.000000      6.000000      4.000000   

       ...      FISTDATE      NEXTDATE       TIMELAG       AVGGIFT  \
count  ...  95412.000000  85439.000000  85439.000000  95412.000000   
mean   ...   9135.651648   9151.022917      8.093739     13.347786   
std    ...    320.394019    294.257260      8.213242     10.769997   
min    ...      0.000000   7211.000000      0.000000      1.285714   
25%    ...   8810.000000   8903.000000      4.000000      8.384615   
50%    ...   9201.000000   9204.000000      6.000000     11.636364   
75%    ...   9409.000000   9409.000000     11.000000     15.477955   
max    ...   9603.000000   9702.000000   1088.000000   1000.000000   

            CONTROLN      TARGET_B      TARGET_D      HPHONE_D        RFA_2F  \
count   95412.000000  95412.000000  95412.000000  95412.000000  95412.000000   
mean    95778.176959      0.050759      0.793073      0.500618      1.910053   
std     55284.596094      0.219506      4.429725      0.500002      1.072749   
min         1.000000      0.000000      0.000000      0.000000      1.000000   
25%     47910.750000      0.000000      0.000000      0.000000      1.000000   
50%     95681.500000      0.000000      0.000000      1.000000      2.000000   
75%    143643.500000      0.000000      0.000000      1.000000      3.000000   
max    191779.000000      1.000000    200.000000      1.000000      4.000000   

           CLUSTER2  
count  95280.000000  
mean      31.533711  
std       18.764614  
min        1.000000  
25%       15.000000  
50%       32.000000  
75%       49.000000  
max       62.000000  

[8 rows x 407 columns]

In [5]:
# Select numericals
num = data.select_dtypes(np.number)
num.head()

ODATEDW  TCODE   DOB   AGE  NUMCHLD  INCOME  WEALTH1  HIT  MBCRAFT  \
0     8901      0  3712  60.0      NaN     NaN      NaN    0      NaN   
1     9401      1  5202  46.0      1.0     6.0      9.0   16      0.0   
2     9001      1     0   NaN      NaN     3.0      1.0    2      0.0   
3     8701      0  2801  70.0      NaN     1.0      4.0    2      0.0   
4     8601      0  2001  78.0      1.0     3.0      2.0   60      1.0   

   MBGARDEN  ...  FISTDATE  NEXTDATE  TIMELAG    AVGGIFT  CONTROLN  TARGET_B  \
0       NaN  ...      8911    9003.0      4.0   7.741935     95515         0   
1       0.0  ...      9310    9504.0     18.0  15.666667    148535         0   
2       0.0  ...      9001    9101.0     12.0   7.481481     15078         0   
3       0.0  ...      8702    8711.0      9.0   6.812500    172556         0   
4       0.0  ...      7903    8005.0     14.0   6.864865      7112         0   

   TARGET_D  HPHONE_D  RFA_2F  CLUSTER2  
0       0.0         0       4      39.0  
1       0.0         0       2       1.0  
2       0.0         1       4      60.0  
3       0.0         1       4      41.0  
4       0.0         1       2      26.0  

[5 rows x 407 columns]

In [6]:
# Check for null values in the numerical columns
num.isna().sum()

ODATEDW         0
TCODE           0
DOB             0
AGE         23665
NUMCHLD     83026
            ...  
TARGET_B        0
TARGET_D        0
HPHONE_D        0
RFA_2F          0
CLUSTER2      132
Length: 407, dtype: int64

In [7]:
num_nulls = num.columns[num.isna().sum()>0]
len(num_nulls)

91

In [8]:
num_nulls.unique()

Index(['AGE', 'NUMCHLD', 'INCOME', 'WEALTH1', 'MBCRAFT', 'MBGARDEN', 'MBBOOKS',
       'MBCOLECT', 'MAGFAML', 'MAGFEM', 'MAGMALE', 'PUBGARDN', 'PUBCULIN',
       'PUBHLTH', 'PUBDOITY', 'PUBNEWFN', 'PUBPHOTO', 'PUBOPP', 'WEALTH2',
       'MSA', 'ADI', 'DMA', 'ADATE_3', 'ADATE_4', 'ADATE_5', 'ADATE_6',
       'ADATE_7', 'ADATE_8', 'ADATE_9', 'ADATE_10', 'ADATE_11', 'ADATE_12',
       'ADATE_13', 'ADATE_14', 'ADATE_15', 'ADATE_16', 'ADATE_17', 'ADATE_18',
       'ADATE_19', 'ADATE_20', 'ADATE_21', 'ADATE_22', 'ADATE_23', 'ADATE_24',
       'RDATE_3', 'RDATE_4', 'RDATE_5', 'RDATE_6', 'RDATE_7', 'RDATE_8',
       'RDATE_9', 'RDATE_10', 'RDATE_11', 'RDATE_12', 'RDATE_13', 'RDATE_14',
       'RDATE_15', 'RDATE_16', 'RDATE_17', 'RDATE_18', 'RDATE_19', 'RDATE_20',
       'RDATE_21', 'RDATE_22', 'RDATE_23', 'RDATE_24', 'RAMNT_3', 'RAMNT_4',
       'RAMNT_5', 'RAMNT_6', 'RAMNT_7', 'RAMNT_8', 'RAMNT_9', 'RAMNT_10',
       'RAMNT_11', 'RAMNT_12', 'RAMNT_13', 'RAMNT_14', 'RAMNT_15', 'RAMNT_16',
    

In [9]:
# Clean column `GEOCODE2`
data.GEOCODE2.value_counts()

A    34484
B    28505
D    16580
C    15524
       187
Name: GEOCODE2, dtype: int64

In [10]:
# Replace NaN value with "U"(=unkown)
data.GEOCODE2 = data.GEOCODE2.replace(" ", "U")
data.GEOCODE2.value_counts()

A    34484
B    28505
D    16580
C    15524
U      187
Name: GEOCODE2, dtype: int64

In [11]:
# Clean column `WEALTH1`
data.WEALTH1.unique()

array([nan,  9.,  1.,  4.,  2.,  6.,  0.,  5.,  8.,  3.,  7.])

In [12]:
data.WEALTH1.value_counts()

9.0    7585
8.0    6793
7.0    6198
6.0    5825
5.0    5280
4.0    4810
3.0    4237
2.0    4085
1.0    3454
0.0    2413
Name: WEALTH1, dtype: int64

In [13]:
data.WEALTH1.isna().sum()

44732

In [14]:
# Split the num into complete and incomplete data
data_complete = data.select_dtypes(np.number).dropna(subset=['WEALTH1'])
data_incomplete = data.select_dtypes(np.number)[data['WEALTH1'].isna()]

In [15]:
# X-y Split
X_complete = data_complete.drop(['WEALTH1'], axis=1)
y_complete = data_complete['WEALTH1']

In [16]:
# Train the XGBoost model
model = xgb.XGBClassifier()
model.fit(X_complete, y_complete)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [17]:
# Predict the missing values
X_incomplete = data_incomplete.drop(['WEALTH1'], axis=1)
predicted_values = model.predict(X_incomplete)

In [18]:
# Check accuracy and classification report
y_true = data_complete['WEALTH1']
y_pred = model.predict(X_complete)
accuracy = accuracy_score(y_true, y_pred)
classification_report = classification_report(y_true, y_pred)
print('Accuracy:', accuracy)
print('Classification Report:\n', classification_report)

Accuracy: 0.9488555643251776
Classification Report:
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      2413
         1.0       0.98      0.99      0.98      3454
         2.0       0.96      0.97      0.97      4085
         3.0       0.95      0.95      0.95      4237
         4.0       0.93      0.93      0.93      4810
         5.0       0.93      0.91      0.92      5280
         6.0       0.93      0.90      0.92      5825
         7.0       0.93      0.93      0.93      6198
         8.0       0.94      0.96      0.95      6793
         9.0       0.98      0.98      0.98      7585

    accuracy                           0.95     50680
   macro avg       0.95      0.95      0.95     50680
weighted avg       0.95      0.95      0.95     50680



In [19]:
# Replace the missing values with the predicted values
data.loc[data['WEALTH1'].isna(), 'WEALTH1'] = predicted_values

In [20]:
data.WEALTH1.value_counts()

9.0    12196
8.0    11607
7.0    10613
6.0    10510
5.0     9847
4.0     9634
2.0     9238
3.0     8954
1.0     7553
0.0     5260
Name: WEALTH1, dtype: int64

**`ADI`**:Area Deprivation Index
<br>It allows for rankings of neighborhoods by socioeconomic disadvantage in a region of interest (e.g. at the state or national level). It includes factors for the theoretical domains of income, education, employment, and housing quality.

In [21]:
# Clean column `ADI`
data.ADI.unique()

array([177.,  13., 281.,  67., 127., 185.,  91., 251., 391., 181., 269.,
        83., 107., 249., 291.,  57., 227., 329., 351.,  55., 133.,  51.,
        73., 159., 201.,  75., 233., 591., 203., 175.,  59., 105., 111.,
       173., 415., 323., 187.,  65., 412., 109., 425., 405., 197., 279.,
       645., 207.,  89., 361., 209., 213.,  15.,  21., 113., 131., 469.,
       199., 129., 441., 459., 235., 301.,  39., 429., 285., 245., 335.,
       393., 577., 439., 455., 383., 263.,   0., 427., 307., 275., 119.,
       229., 273., 325., 371., 377., 315., 342., 421., 219.,  61.,  93.,
       375., 283., 381., 243., 353., 613., 339., 367., 417., 299., 271.,
       157.,  77., 327.,  53.,  87., 451., 627.,  71., 253., 363., 403.,
       115., 389.,  63., 321., 448., 237., 217., 241., 123., 221., 165.,
       277.,  85., 319., 247.,  69., 379.,  95.,  17., 625., 462., 303.,
       179., 331., 231., 337., 257., 409., 457., 359., 373.,  nan, 413.,
       215., 205., 313., 211., 305., 355., 419., 47

In [22]:
data.ADI.isna().sum()

132

In [23]:
# Drop rows where ADI has missing values
data = data.dropna(subset=['ADI'])

**`DMA`**: Designated Market Area
<br>A Designated Market Area (often referred to as DMA) is an advertising term that stands for different regions in the United States divided into separate marketing areas. There are 210 distinct regions and each Designated Market Area has a 3-digit numeric code.

In [24]:
# Clean column `DMA`
data.DMA.unique()

array([682., 803., 518., 862., 528., 691., 509., 643., 624., 659., 671.,
       527., 613., 716., 770., 505., 717., 534., 560., 547., 571., 602.,
       800., 638., 618., 609., 820., 821., 635., 675., 563., 819., 617.,
       637., 606., 709., 632., 807., 698., 623., 507., 627., 524., 517.,
       539., 649., 868., 546., 529., 567., 825., 512., 669., 764., 575.,
       548., 662., 811., 801., 652., 771., 603., 556., 622., 561., 724.,
       804., 633., 839., 686., 650., 743., 619., 678., 753., 610., 745.,
       604., 749., 670., 765., 711., 553., 762., 520., 503., 551., 515.,
       647., 544.,   0., 676., 752., 545., 754., 810., 790., 656., 755.,
       641., 616., 628., 588., 581., 540., 658., 583., 866., 642., 746.,
       634., 648., 705., 725., 744., 513., 612., 813., 531., 751., 500.,
       630., 611., 789., 582., 693., 692., 828., 626., 710., 542., 855.,
       687., 679., 640., 722., 620., 881., 564., 522., 756., 570., 718.,
       530., 557., 625., 541., 657., 631., 550., 52

In [25]:
data.DMA.isna().sum()

0